# Generated by Django 5.2.8 on 2025-11-08 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '__first__'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, help_text='URL de la portada del álbum', max_length=500, null=True)),
                ('release_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('retired', 'Retirado')], default='draft', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del álbum en la moneda base', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artist.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='albums', to='genre.genre')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'db_table': 'albums',
                'ordering': ['-release_date', 'title'],
            },
        ),
    ]
