# Generated by Django 5.2.8 on 2025-11-10 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('label_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.EmailField(blank=True, max_length=200)),
                ('web', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_labels', to='country.country')),
            ],
            options={
                'verbose_name': 'Sello Discográfico',
                'verbose_name_plural': 'Sellos Discográficos',
                'db_table': 'record_labels',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='record_labe_name_8ca9ad_idx'), models.Index(fields=['country'], name='record_labe_country_631868_idx'), models.Index(fields=['created_at'], name='record_labe_created_dee4e1_idx')],
            },
        ),
    ]
