# Generated by Django 5.2.8 on 2025-11-10 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '__first__'),
        ('record_label', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('image_url', models.URLField(default='https://static.vecteezy.com/system/resources/previews/036/280/651/original/default-avatar-profile-icon-social-media-user-image-gray-avatar-icon-blank-profile-silhouette-illustration-vector.jpg')),
                ('socials', models.JSONField(blank=True, default=dict, help_text="Diccionario con las redes sociales: {'twitter': 'url', ...}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='country.country')),
                ('label_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='record_label.recordlabel')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'db_table': 'artists',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='artists_name_b2ca99_idx'), models.Index(fields=['country'], name='artists_country_c20e65_idx'), models.Index(fields=['label_id'], name='artists_label_i_4e627c_idx')],
            },
        ),
    ]
