# Generated by Django 5.2.8 on 2025-11-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '__first__'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('explicit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('retired', 'Retirado')], default='published', max_length=10)),
                ('preview_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('audio_master_url', models.URLField(max_length=1000)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('de', 'Alemán'), ('it', 'Italiano'), ('pt', 'Portugués'), ('ja', 'Japonés'), ('ko', 'Coreano'), ('zh', 'Chino'), ('ru', 'Ruso'), ('ar', 'Árabe'), ('hi', 'Hindi')], default='en', max_length=2)),
                ('album_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='album.album')),
                ('artist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='artist.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='tracks', to='genre.genre')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='tracks_title_f94b39_idx'), models.Index(fields=['status'], name='tracks_status_459eda_idx'), models.Index(fields=['artist_id', 'album_id'], name='tracks_artist__22e5cd_idx')],
            },
        ),
    ]
