# Generated by Django 5.2.8 on 2025-11-10 17:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del género musical', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del género musical', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='genre.genre', verbose_name='Género padre')),
            ],
            options={
                'verbose_name': 'Género Musical',
                'verbose_name_plural': 'Géneros Musicales',
                'db_table': 'genres',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='genres_name_4778a7_idx'), models.Index(fields=['parent_genre'], name='genres_parent__9552df_idx')],
            },
        ),
    ]
