# Generated by Django 5.2.8 on 2025-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, help_text='ID del usuario en el microservicio de autenticación (formato string)', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'playlists',
                'indexes': [models.Index(fields=['owner_id', 'created_at'], name='playlists_owner_i_218da9_idx'), models.Index(fields=['owner_id', 'is_public'], name='playlists_owner_i_28eeb7_idx')],
            },
        ),
    ]
